/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ActionTestPerformanceMetricSummary {
  displayName: string;
  unitOfMeasurement: string;
  measurements: number[];
  identifier?: string;
  baselineName?: string;
  baselineAverage?: number;
  maxPercentRegression?: number;
  maxPercentRelativeStandardDeviation?: number;
  maxRegression?: number;
  maxStandardDeviation?: number;
  polarity?: string;
}
