/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ActivityLogAnalyzerControlFlowStep {
  parentIndex: number
  title: string
  startLocation?: DocumentLocation
  endLocation?: DocumentLocation
  edges: ActivityLogAnalyzerControlFlowStepEdge[]
}
export interface DocumentLocation {
  url: string
  concreteTypeName: string
}
export interface ActivityLogAnalyzerControlFlowStepEdge {
  startLocation?: DocumentLocation
  endLocation?: DocumentLocation
}
