/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ActivityLogAnalyzerResultMessage {
  type: string
  title: string
  shortTitle?: string
  category?: string
  location?: DocumentLocation
  annotations: ActivityLogMessageAnnotation[]
  steps: ActivityLogAnalyzerStep[]
  resultType?: string
  keyEventIndex: number
}
export interface DocumentLocation {
  url: string
  concreteTypeName: string
}
export interface ActivityLogMessageAnnotation {
  title: string
  location?: DocumentLocation
}
export interface ActivityLogAnalyzerStep {
  parentIndex: number
}
