/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ActionResult {
  resultName: string;
  status: string;
  metrics: ResultMetrics;
  issues: ResultIssueSummaries;
  coverage: CodeCoverageInfo;
  timelineRef?: Reference;
  logRef?: Reference;
  testsRef?: Reference;
  diagnosticsRef?: Reference;
}
export interface ResultMetrics {
  analyzerWarningCount: number;
  errorCount: number;
  testsCount: number;
  testsFailedCount: number;
  testsSkippedCount: number;
  warningCount: number;
}
export interface ResultIssueSummaries {
  analyzerWarningSummaries: IssueSummary[];
  errorSummaries: IssueSummary[];
  testFailureSummaries: TestFailureIssueSummary[];
  warningSummaries: IssueSummary[];
}
export interface IssueSummary {
  issueType: string;
  message: string;
  producingTarget?: string;
  documentLocationInCreatingWorkspace?: DocumentLocation;
}
export interface DocumentLocation {
  url: string;
  concreteTypeName: string;
}
export interface TestFailureIssueSummary {
  issueType: string;
  message: string;
  producingTarget?: string;
  documentLocationInCreatingWorkspace?: DocumentLocation;
  testCaseName: string;
}
export interface CodeCoverageInfo {
  hasCoverageData: boolean;
  reportRef?: Reference;
  archiveRef?: Reference;
}
export interface Reference {
  id: string;
  targetType?: TypeDefinition;
}
export interface TypeDefinition {
  name: string;
  supertype?: TypeDefinition;
}
