/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ActionTestMetadata {
  name?: string
  identifier?: string
  testStatus: string
  duration?: number
  summaryRef?: Reference
  performanceMetricsCount: number
  failureSummariesCount: number
  activitySummariesCount: number
}
export interface Reference {
  id: string
  targetType?: TypeDefinition
}
export interface TypeDefinition {
  name: string
  supertype?: TypeDefinition
}
